[package]
name         = "hermes-solomachine-relayer"
version      = { workspace = true }
edition      = { workspace = true }
license      = { workspace = true }
keywords     = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
description  = "An IBC relayer for relaying between Cosmos and Solomachin clients."

[dependencies]
cgp                                 = { workspace = true }
hermes-prelude                      = { workspace = true }
hermes-runtime-components           = { workspace = true }
hermes-logging-components           = { workspace = true }
hermes-solomachine-chain-components = { workspace = true }
hermes-cosmos-relayer               = { workspace = true }
hermes-cosmos-chain-components      = { workspace = true }
hermes-cosmos-chain-preset          = { workspace = true }
hermes-error                        = { workspace = true }
hermes-runtime                      = { workspace = true }
hermes-tracing-logging-components   = { workspace = true }
hermes-relayer-components           = { workspace = true }
hermes-core                         = { workspace = true }
hermes-relayer-components-extra     = { workspace = true }
hermes-encoding-components          = { workspace = true }
hermes-protobuf-encoding-components = { workspace = true }

ibc        = { workspace = true }
ibc-proto  = { workspace = true }
tendermint = { workspace = true, features = [ "secp256k1" ] }

serde        = { workspace = true }
serde_derive = { workspace = true }
prost        = { workspace = true }
eyre         = { workspace = true }
tokio        = { workspace = true }
itertools    = { workspace = true }
futures      = { workspace = true }
tracing      = { workspace = true }
secp256k1    = { workspace = true, features = [ "rand" ] }

sha2        = "0.10.7"
crypto-hash = "0.3.4"
bytes       = { version = "1.8.0" }
