[package]
name = "hermes-wasm-chain-components"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }
description = """
    Context-generic chain components related to CosmWasm
"""

[dependencies]
hermes-core    = { workspace = true }
hermes-cosmos-chain-components      = { workspace = true }
hermes-prelude = { workspace = true }

ibc              = { workspace = true, features = [ "borsh", "schema", "serde" ] }
ibc-proto  = { workspace = true }
sha2         = { workspace = true }
tendermint-proto = { workspace = true }
tokio        = { workspace = true }

prost = { workspace = true }
