[package]
name = "hermes-cosmos"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }
description = """
    Implementation of an IBC Relayer in Rust, as a library
"""

[dependencies]
hermes-core                       = { workspace = true }
hermes-cosmos-core                = { workspace = true }
hermes-cosmos-integration-tests   = { workspace = true }
hermes-cosmos-relayer             = { workspace = true }
hermes-cosmos-wasm-relayer        = { workspace = true }
hermes-runtime                    = { workspace = true }
hermes-error                      = { workspace = true }
hermes-comet-light-client-context = { workspace = true }
