[package]
name         = "hermes-protobuf-encoding-components"
version      = { workspace = true }
edition      = { workspace = true }
license      = { workspace = true }
keywords     = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
readme       = "README.md"
description  = """
    Implementation of an IBC Relayer in Rust, as a library
"""

[dependencies]
cgp-core                    = { workspace = true }
hermes-encoding-components  = { workspace = true }

prost                       = { workspace = true }
prost-types                 = { workspace = true }