name: Integration Tests
on:
  pull_request: {}
  push:
    branches: main

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 1
  CARGO_PROFILE_RELEASE_DEBUG: 1
  RUST_BACKTRACE: short
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

# Cancel previous runs of this workflow when a new commit is added to the PR, branch or tag
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration-test:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        chain:
          - package: gaia14
            command: gaiad
            account_prefix: cosmos
            features: ''
          - package: ibc-go-v7-simapp
            command: simd
            account_prefix: cosmos
            features: solomachine
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v12
        with:
          name: cosmos
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p ibc-integration-test --no-fail-fast --no-run --features=${{ matrix.chain.features }}
      - name: run integration tests
        env:
          RUST_LOG: info,ibc_relayer_runtime=trace
          RUST_BACKTRACE: 1
          NO_COLOR_LOG: 1
          CHAIN_COMMAND_PATHS: ${{ matrix.chain.command }}
          ACCOUNT_PREFIXES: ${{ matrix.chain.account_prefix }}
        run: |
            nix shell .#${{ matrix.chain.package }} -c cargo \
              test -p ibc-integration-test --features=${{ matrix.chain.features }} --no-fail-fast -- \
              --nocapture --test-threads=2
